[build]
  command = "cd client && npm install && npm run build && cd ../netlify/functions && npm install"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
